title: Your awesome title

exclude:
  - assets/css
  - assets/javascript
  - package.json
  - package-lock.json
  - postcss.config.mjs
  - Procfile
  - tailwind.config.js
keep_files:
  - assets/css
  - assets/javascript
